workflows:
  android-workflow:
    name: Final No Error Build
    max_build_duration: 20
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Clean and Create Android
        script: |
          rm -rf android
          flutter create . --platforms=android --project-name egg_treat_customer
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.apk
