workflows:
  android-workflow:
    name: Android Firebase LIVE
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Create Android Folder
        script: |
          flutter create . --platforms=android
          cp google-services.json android/app/google-services.json || echo "copied"
      - name: Fix V1 Embedding and Kotlin Issue
        script: |
          sed -i '' 's/compileSdkVersion.*/compileSdkVersion 34/' android/app/build.gradle || sed -i 's/compileSdkVersion.*/compileSdkVersion 34/' android/app/build.gradle
          sed -i '' 's/minSdkVersion.*/minSdkVersion 21/' android/app/build.gradle || sed -i 's/minSdkVersion.*/minSdkVersion 21/' android/app/build.gradle
      - name: Get Packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - ashok@example.com
