name: egg_treat_customer
description: Egg Treat Customer App - Live Firebase
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  cloud_firestore: ^4.15.0
flutter:
  uses-material-design: true
